# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# insert full languages for tesseract
Language.create(short: "ara",      full: "Arabic", enabled: false) 
Language.create(short: "aze", 	   full: "Azerbauijani", enabled: false) 
Language.create(short: "bul", 	   full: "Bulgarian", enabled: false) 
Language.create(short: "cat", 	   full: "Catalan", enabled: false) 
Language.create(short: "ces", 	   full: "Czech", enabled: false) 
Language.create(short: "chi_sim",  full: "Simplified Chinese", enabled: false) 
Language.create(short: "chi_tra",  full: "Traditional Chinese", enabled: false) 
Language.create(short: "chr", 	   full: "Cherokee", enabled: false) 
Language.create(short: "dan", 	   full: "Danish", enabled: false) 
Language.create(short: "dan-frak", full: "Danish (Fraktur)", enabled: false) 
Language.create(short: "deu", 	   full: "German", enabled: false) 
Language.create(short: "ell", 	   full: "Greek", enabled: false) 
Language.create(short: "eng", 	   full: "English", enabled: true) 
Language.create(short: "enm", 	   full: "Old English", enabled: false) 
Language.create(short: "epo", 	   full: "Esperanto", enabled: false) 
Language.create(short: "est", 	   full: "Estonian", enabled: false) 
Language.create(short: "fin", 	   full: "Finnish", enabled: false) 
Language.create(short: "fra", 	   full: "French", enabled: false) 
Language.create(short: "frm", 	   full: "Old French", enabled: false) 
Language.create(short: "glg", 	   full: "Galician", enabled: false) 
Language.create(short: "heb", 	   full: "Hebrew", enabled: false) 
Language.create(short: "hin", 	   full: "Hindi", enabled: false) 
Language.create(short: "hrv", 	   full: "Croation", enabled: false) 
Language.create(short: "hun", 	   full: "Hungarian", enabled: false) 
Language.create(short: "ind", 	   full: "Indonesian", enabled: false) 
Language.create(short: "ita", 	   full: "Italian", enabled: false) 
Language.create(short: "jpn", 	   full: "Japanese", enabled: false) 
Language.create(short: "kor", 	   full: "Korean", enabled: false) 
Language.create(short: "lav", 	   full: "Latvian", enabled: false) 
Language.create(short: "lit", 	   full: "Lithuanian", enabled: false) 
Language.create(short: "nld", 	   full: "Dutch", enabled: false) 
Language.create(short: "nor", 	   full: "Norwegian", enabled: false) 
Language.create(short: "pol", 	   full: "Polish", enabled: false) 
Language.create(short: "por", 	   full: "Portuguese", enabled: false) 
Language.create(short: "ron", 	   full: "Romanian", enabled: false) 
Language.create(short: "rus", 	   full: "Russian", enabled: false) 
Language.create(short: "slk", 	   full: "Slovakian", enabled: false) 
Language.create(short: "slv", 	   full: "Slovenian", enabled: false) 
Language.create(short: "sqi", 	   full: "Albanian", enabled: false) 
Language.create(short: "spa", 	   full: "Spanish", enabled: true) 
Language.create(short: "srp", 	   full: "Serbian", enabled: false) 
Language.create(short: "swe", 	   full: "Swedish", enabled: true) 
Language.create(short: "tam", 	   full: "Tamil", enabled: false) 
Language.create(short: "tel", 	   full: "Telugu", enabled: false) 
Language.create(short: "tgl", 	   full: "Tagalog", enabled: false) 
Language.create(short: "tha", 	   full: "Thai", enabled: false) 
Language.create(short: "tur", 	   full: "Turkish", enabled: false) 
Language.create(short: "ukr", 	   full: "Ukrainian", enabled: false) 
Language.create(short: "vie", 	   full: "Vietnamese", enabled: false) 

# add the phases of document conversion lifecycle
Phase.create(id: 1, name: "uploaded")
Phase.create(id: 2, name: "preprocessing")
Phase.create(id: 3, name: "reprocessing")
Phase.create(id: 4, name: "ready")
Phase.create(id: 5, name: "extracting")
Phase.create(id: 6, name: "extracted")


#Tyndale.create(short: "", full: "Afrikaans", enabled: true)
#Tyndale.create(short: "", full: "Albanian", enabled: true)
#Tyndale.create(short: "", full: "Arabic", enabled: true)
#Tyndale.create(short: "", full: "Belarusian", enabled: true)
#Tyndale.create(short: "", full: "Bulgarian", enabled: true)
#Tyndale.create(short: "", full: "Catalan", enabled: true)
#Tyndale.create(short: "", full: "Simplified_chinese", enabled: true)
#Tyndale.create(short: "", full: "Traditional_chinese", enabled: true)
#Tyndale.create(short: "", full: "Croatian", enabled: true)
#Tyndale.create(short: "", full: "Czech", enabled: true)
#Tyndale.create(short: "", full: "Danish", enabled: true)
#Tyndale.create(short: "", full: "Dutch", enabled: true)
#Tyndale.create(short: "", full: "English", enabled: true)
#Tyndale.create(short: "", full: "Estonian", enabled: true)
#Tyndale.create(short: "", full: "Filipino", enabled: true)
#Tyndale.create(short: "", full: "Finnish", enabled: true)
#Tyndale.create(short: "", full: "French", enabled: true)
#Tyndale.create(short: "", full: "Galician", enabled: true)
#Tyndale.create(short: "", full: "German", enabled: true)
#Tyndale.create(short: "", full: "Greek", enabled: true)
#Tyndale.create(short: "", full: "Haitian_creole", enabled: true)
#Tyndale.create(short: "", full: "Hebrew", enabled: true)
#Tyndale.create(short: "", full: "Hindi", enabled: true)
#Tyndale.create(short: "", full: "Hungarian", enabled: true)
#Tyndale.create(short: "", full: "Icelandic", enabled: true)
#Tyndale.create(short: "", full: "Indonesian", enabled: true)
#Tyndale.create(short: "", full: "Irish", enabled: true)
#Tyndale.create(short: "", full: "Italian", enabled: true)
#Tyndale.create(short: "", full: "Japanese", enabled: true)
#Tyndale.create(short: "", full: "Latvian", enabled: true)
#Tyndale.create(short: "", full: "Lithuanian", enabled: true)
#Tyndale.create(short: "", full: "Macedonian", enabled: true)
#Tyndale.create(short: "", full: "Malay", enabled: true)
#Tyndale.create(short: "", full: "Maltese", enabled: true)
#Tyndale.create(short: "", full: "Norwegian", enabled: true)
#Tyndale.create(short: "", full: "Persian", enabled: true)
#Tyndale.create(short: "", full: "Polish", enabled: true)
#Tyndale.create(short: "", full: "Portuguese", enabled: true)
#Tyndale.create(short: "", full: "Romanian", enabled: true)
#Tyndale.create(short: "", full: "Russian", enabled: true)
#Tyndale.create(short: "", full: "Serbian", enabled: true)
#Tyndale.create(short: "", full: "Slovak", enabled: true)
#Tyndale.create(short: "", full: "Slovenian", enabled: true)
#Tyndale.create(short: "", full: "Spanish", enabled: true)
#Tyndale.create(short: "", full: "Swahili", enabled: true)
#Tyndale.create(short: "", full: "Swedish", enabled: true)
#Tyndale.create(short: "", full: "Thai", enabled: true)
#Tyndale.create(short: "", full: "Turkish", enabled: true)
#Tyndale.create(short: "", full: "Ukrainian", enabled: true)
#Tyndale.create(short: "", full: "Vietnamese", enabled: true)
#Tyndale.create(short: "", full: "Welsh", enabled: true)
#Tyndale.create(short: "", full: "Yiddish", enabled: true)












